### ISSUE TITLE
Spacy?

### ISSUE THREAD

**Issue by yuchenlin** [swapnilg915/cosine_similarity_using_embeddings#1]
Hi thanks for the great repo.

I found that there is `spacy` in the readme but the code cannot be found in the repo.

**Comment by swapnilg915** [comment]
Hi Yuchen,

Thanks for the feedback. Will add the code for Spacy embeddings ASAP. Will
let you know once it's done.

Regrads,
Swapnil

**Comment by swapnilg915** [comment]
Hi Yuchen,

The code with spacy embeddings is added. 

Regrads,
Swapnil
